### ISSUE TITLE
Question Regarding Animechan Deployment

### ISSUE THREAD

**Issue by MuddassirAsh** [rocktimsaikia/animechan#98]
Hey, I am considering deploying a hobby-project of a simple API of quotes from Presidents.

I was wondering, how did you deploy Animechan? I am currently using FastAPI and was considering between EC2 or Lambda and just wanted your thoughts and how you did yours.

**Comment by melosh101** [comment]
I recommend taking a look at the deploy workflow located in /.github/workflows/deploy.yml

**Comment by rocktimsaikia** [comment]
@MuddassirAsh If you just want to host your hobby server somewhere, you can use cloud services like heroku or render etc. I would not recommend aws services for a simple hobby project. As you will be billed on a lot of interconnected services from aws (assuming you will add a domain also) plus the maintenance of the whole thing from deploy to every tiny detail can distract you from your main goal. The reason im hosting in ec2 is because it has a lot of high traffic and I have some big future plans with this project which requires me to have complete flexibility over the complete infrastructure.

> You can ask these sort of general questions which are not related to Animechan directly in discord, right people will respond there.
